### PR TITLE
Fix facebook counter url

### PR DESCRIPTION
**Pull request by xdimedrolx**
REST API is deprecated for versions v2.1 and higher (12)

### CODE REVIEW

**Comment by sapegin** [comment]
Should we change the host again? See #184.

**Comment by xdimedrolx** [comment]
Yes, we should change url.
Rest api is now deprecated, no longer works.
e.g., for
https://api.facebook.com/restserver.php?format=json&method=links.getStats&urls=https://github.com
The result is:
`{
error_code: 12,
error_msg: "REST API is deprecated for versions v2.1 and higher (12)",
request_args: [
{
key: "format",
value: "json"
},
{
key: "method",
value: "links.getStats"
},
{
key: "urls",
value: "https://github.com"
}
]
}`

**Comment by sapegin** [comment]
Interesting. Version 2.1 of what? :-)

**Comment by gldmtr** [comment]
Version 2.1 of FB api. That was my bad. But I have not seen any info about rest-api deprecation.

**Pull request merged**
